export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE';
export const SET_SORT_BY = 'SET_SORT_BY';
export const FETCH_PART_EMPLOYEE_SUCCESS = 'FETCH_PART_EMPLOYEE_SUCCESS';
export const FETCH_PART_SEARCH_AND_SORT_EMPLOYEE_SUCCESS = 'FETCH_PART_SEARCH_AND_SORT_EMPLOYEE_SUCCESS';
export const FETCH_PART_SEARCH_EMPLOYEE_SUCCESS = 'FETCH_PART_SEARCH_EMPLOYEE_SUCCESS';
export const FETCH_PART_SORT_EMPLOYEE_SUCCESS = 'FETCH_PART_SORT_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_BY_ID_SUCCESS = 'FETCH_EMPLOYEE_BY_ID_SUCCESS';

///--------------------------///

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

///--------------------------///

export const FETCH_SICKLEAVES = 'FETCH_SICKLEAVES';
export const FETCH_PART_SICKLEAVES_SUCCESS = 'FETCH_PART_SICKLEAVES_SUCCESS';
export const FETCH_SORTED_PART_SICKLEAVES_SUCCESS = 'FETCH_SORTED_PART_SICKLEAVES_SUCCESS';
export const FETCH_SICKLEAVES_FAILURE = 'FETCH_SICKLEAVES_FAILURE';
export const FETCH_SEARCH_AND_SORT_SUCCESS = 'FETCH_SEARCH_AND_SORT_SUCCESS';
export const FETCH_SEARCH_PART_SUCCESS = 'FETCH_SEARCH_PART_SUCCESS';
export const FETCH_SICKLEVAES_BY_ID_SUCCESS = 'FETCH_SICKLEVAES_BY_ID_SUCCESS';

///--------------------------///

export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENT_BY_ID_SUCCESS = 'FETCH_DOCUMENT_BY_ID_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

///--------------------------///

export const FETCH_VACATIONS = 'FETCH_VACATIONS';
export const FETCH_PART_VACATIONS_SUCCESS = 'FETCH_PART_VACATIONS_SUCCESS';
export const FETCH_SORTED_PART_VACATIONS_SUCCESS = 'FETCH_SORTED_PART_VACATIONS_SUCCESS';
export const FETCH_VACATIONS_SUCCESS = 'FETCH_VACATIONS_SUCCESS';
export const FETCH_SEARCH_AND_SORT_SUCCESS_VACATIONS = 'FETCH_SEARCH_AND_SORT_SUCCESS_VACATIONS';
export const FETCH_SEARCH_PART_SUCCESS_VACATIONS = 'FETCH_SEARCH_PART_SUCCESS_VACATIONS';
export const FETCH_VACATIONS_FAILURE = 'FETCH_VACATIONS_FAILURE';
export const FETCH_VACATIONS_BY_ID_SUCCESS = 'FETCH_VACATIONS_BY_ID_SUCCESS';

///--------------------------///

export const FETCH_DAYSOFF = 'FETCH_DAYSOFF';
export const FETCH_PART_DAYSOFF_SUCCESS = 'FETCH_PART_DAYSOFF_SUCCESS';
export const FETCH_SORTED_PART_DAYSOFF_SUCCESS = 'FETCH_SORTED_PART_DAYSOFF_SUCCESS';
export const FETCH_DAYSOFF_SUCCESS = 'FETCH_DAYSOFF_SUCCESS';
export const FETCH_SEARCH_AND_SORT_SUCCESS_DAYSOFF = 'FETCH_SEARCH_AND_SORT_SUCCESS_DAYSOFF';
export const FETCH_SEARCH_PART_SUCCESS_DAYSOFF = 'FETCH_SEARCH_PART_SUCCESS_DAYSOFF';
export const FETCH_DAYSOFF_FAILURE = 'FETCH_DAYSOFF_FAILURE';
export const FETCH_DAYSOFF_BY_ID_SUCCESS = 'FETCH_DAYSOFF_BY_ID_SUCCESS';

///--------------------------///

export const FETCH_DATA_CHANGES= 'FETCH_DATA_CHANGES';
export const FETCH_PART_DATA_CHANGES_SUCCESS = 'FETCH_PART_DATA_CHANGES_SUCCESS';
export const FETCH_SORTED_PART_DATA_CHANGES_SUCCESS = 'FETCH_SORTED_PART_DATA_CHANGES_SUCCESS';
export const FETCH_DATA_CHANGES_SUCCESS = 'FETCH_DATA_CHANGES_SUCCESS';
export const FETCH_SEARCH_AND_SORT_DATA_CHANGES_SUCCESS = 'FETCH_SEARCH_AND_SORT_DATA_CHANGES_SUCCESS';
export const FETCH_SEARCH_PART_DATA_CHANGES_SUCCESS = 'FETCH_SEARCH_PART_DATA_CHANGES_SUCCESS';
export const FETCH_DATA_CHANGES_FAILURE = 'FETCH_DATA_CHANGES_FAILURE';

///------------------------///